services:
  backend:
    image: ahamzahhh/coursepage:latest
    ports:
      - 127.0.0.1:8000:8000
    container_name: backend
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    container_name: watchtower