name: Release DevOps with Docker

on:
  push:
    branches:
      - main
    paths:
      - 'express-app/**' # Trigger only when files in the express.app folder change
      - '.github/workflow/workflow-test.yaml'

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./express-app
          file: ./express-app/Dockerfile
          push: true
          tags: ahamzahhh/coursepage:latest
